services:
  plex:
    container_name: plex
    environment:
      - 'ADVERTISE_IP=http://${WAN_IP}:32400'
      - 'PLEX_CLAIM=${PLEX_CLAIM}'
      - 'TZ=${TZ}'
    hostname: 'plex'
    image: 'plexinc/pms-docker'
    ports:
      - '1900:1900/udp'
      - '32400:32400/tcp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
      - '32469:32469/tcp'
      - '8324:8324/tcp'
    restart: 'unless-stopped'
    volumes:
      - './config/plex/config:/config'
      - './config/plex/transcode:/transcode'
      - './downloads:/data'
  qbittorrent-wireguard:
    cap_add:
      - 'NET_ADMIN'
    cap_drop:
      - 'AUDIT_CONTROL'
      - 'BLOCK_SUSPEND'
      - 'DAC_READ_SEARCH'
      - 'IPC_LOCK'
      - 'IPC_OWNER'
      - 'LEASE'
      - 'LINUX_IMMUTABLE'
      - 'MAC_ADMIN'
      - 'MAC_OVERRIDE'
      - 'NET_BROADCAST'
      - 'SYSLOG'
      - 'SYS_ADMIN'
      - 'SYS_BOOT'
      - 'SYS_MODULE'
      - 'SYS_NICE'
      - 'SYS_PACCT'
      - 'SYS_PTRACE'
      - 'SYS_RAWIO'
      - 'SYS_RESOURCE'
      - 'SYS_TIME'
      - 'SYS_TTY_CONFIG'
      - 'WAKE_ALARM'
    container_name: 'qbittorrent-wireguard'
    entrypoint:
      - '/bin/bash'
      - '/start.sh'
    environment:
      - 'ENABLEPROTONVPNPORTFWD=1'
      - 'LAN_NETWORK=${WHITELIST_NETWORKS}'
      - 'PGID=${PGID}'
      - 'PUID=${PUID}'
      - 'QBT_LEGAL_NOTICE=confirm'
      - 'TZ=${TZ}'
      - 'WEBUI_PASS=${WEBUI_PASS}'
      - 'WEBUI_URL=http://${WAN_IP}'
      - 'WEBUI_USER=${WEBUI_USER}'
    image: 'docker.io/tenseiken/qbittorrent-wireguard:latest'
    ipc: 'private'
    network_mode: 'bridge'
    platform: 'linux/amd64'
    ports:
      - '8999:8999/tcp'
      - '8999:8999/udp'
      - '8080:8080/tcp'
    privileged: true
    restart: 'unless-stopped'
    security_opt:
      - 'label=disable'
    stdin_open: true
    sysctls:
      - 'net.ipv4.conf.all.src_valid_mark=1'
    tty: true
    volumes:
      - './downloads:/downloads'
      - './config:/config'
    working_dir: '/opt'
