services:
  nginx-proxy-manager:
    container_name: proxy
    environment:
      - DISABLE_IPV6=true
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 443:443
      - 80:80
      - 81:81
    restart: unless-stopped
    volumes:
      - ./config/proxy/data:/data
      - ./config/proxy/letsencrypt:/etc/letsencrypt
  plex-media-server:
    container_name: plex
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_GID=${PGID}
      - PLEX_UID=${PUID}
      - TZ=${TZ}
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    volumes:
      - ./config/plex/config:/config
      - ./config/plex/transcode:/transcode
      - ./downloads:/data
  qbittorrent-wireguard:
    cap_add:
      - NET_ADMIN
    container_name: torrent
    entrypoint:
      - /bin/bash
      - /start.sh
    environment:
      - ENABLEPROTONVPNPORTFWD=1
      - LAN_NETWORK=${SUBNET}
      - PGID=${PGID}
      - PUID=${PUID}
      - QBT_LEGAL_NOTICE=confirm
      - RESTART_CONTAINER=no
      - TZ=${TZ}
      - WEBUI_PASS=${QBITTORRENT_PASS}
      - WEBUI_URL=${QBITTORRENT_URL}
      - WEBUI_USER=${QBITTORRENT_USER}
    image: docker.io/tenseiken/qbittorrent-wireguard:latest
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./downloads:/downloads
      - ./config/torrent:/config
networks:
  default:
    external: true
    name: tv
